export const Source = {
  IS_INSTALLED_FROM_PLAY_STORE: 'IS_INSTALLED_FROM_PLAY_STORE',
  IS_INSTALLED_FROM_PLAY_PACKAGE_INSTALLER: 'IS_INSTALLED_FROM_PLAY_PACKAGE_INSTALLER',
  IS_INSTALLED_FROM_RU_STORE: 'IS_INSTALLED_FROM_RU_STORE',
  IS_INSTALLED_FROM_LOCAL_SOURCE: 'IS_INSTALLED_FROM_LOCAL_SOURCE',
  IS_INSTALLED_FROM_AMAZON_APP_STORE: 'IS_INSTALLED_FROM_AMAZON_APP_STORE',
  IS_INSTALLED_FROM_HUAWEI_APP_GALLERY: 'IS_INSTALLED_FROM_HUAWEI_APP_GALLERY',
  IS_INSTALLED_FROM_SAMSUNG_GALAXY_STORE: 'IS_INSTALLED_FROM_SAMSUNG_GALAXY_STORE',
  IS_INSTALLED_FROM_SAMSUNG_SMART_SWITCH_MOBILE: 'IS_INSTALLED_FROM_SAMSUNG_SMART_SWITCH_MOBILE',
  IS_INSTALLED_FROM_OPPO_APP_MARKET: 'IS_INSTALLED_FROM_OPPO_APP_MARKET',
  IS_INSTALLED_FROM_XIAOMI_GET_APPS: 'IS_INSTALLED_FROM_XIAOMI_GET_APPS',
  IS_INSTALLED_FROM_VIVO_APP_STORE: 'IS_INSTALLED_FROM_VIVO_APP_STORE',
  IS_INSTALLED_FROM_OTHER_SOURCE: 'IS_INSTALLED_FROM_OTHER_SOURCE',
  IS_INSTALLED_FROM_APP_STORE: 'IS_INSTALLED_FROM_APP_STORE',
  IS_INSTALLED_FROM_TEST_FLIGHT: 'IS_INSTALLED_FROM_TEST_FLIGHT',
  UNKNOWN: 'UNKNOWN'
} as const;

export type Source = typeof Source[keyof typeof Source];
